### ISSUE TITLE
DTLS - Unhandled Exception: System.ArgumentNullException: Buffer cannot be null.

### ISSUE THREAD

**Issue by tsubasamanda** [Sammi-Husky/Sm4sh-Tools#18]
Attempted both running latest release and compiling from source.

**New Information**

Line 15 in Util.cs
Caused by parameter `dec` to be null.

Full trace

```
Patch found: patch/animcmd/fighter/zelda/motion.mtable
Patch found: patch/animcmd/fighter/zelda/sound.bin
Buffer cannot be null.
Parameter name: buffer

Unhandled Exception: System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at DTLS.IO.Util.Compress(Byte[] src)
   at DTLS.Program.PatchArchive(String resourceString, String patchFolder)
   at DTLS.Program.Main(String[] args)
```

**Comment by tsubasamanda** [comment]
Looking back on this, I believe it may have been due to an incomplete RomFS (I remember braindump only running for about 10 minutes). I'll try again with a fresh one.
