### ISSUE TITLE
Opening more than one animation subroutine causes exceptions

### ISSUE THREAD

**Issue by TheGag96** [Sammi-Husky/Sm4sh-Tools#19]
This happens both on the latest release build and the current master branch. These exceptions are thrown right after another:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sm4shCommand.AcmdMain.tabControl1_DrawItem(Object sender, DrawItemEventArgs e)
   at System.Windows.Forms.TabControl.OnDrawItem(DrawItemEventArgs e)
   at System.Windows.Forms.TabControl.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.TabControl.GetTabPage(Int32 index)
   at Sm4shCommand.AcmdMain.tabControl1_DrawItem(Object sender, DrawItemEventArgs e)
   at System.Windows.Forms.TabControl.OnDrawItem(DrawItemEventArgs e)
   at System.Windows.Forms.TabControl.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr     lparam)
```

Often times, the new tab and subroutines will load fine still, oddly enough.

**Comment by Sammi-Husky** [comment]
Fixed with 868d2e
