### ISSUE TITLE
DTLS Error

### ISSUE THREAD

**Issue by LemonatedCat** [Sammi-Husky/Sm4sh-Tools#51]
Whenever i try to unpack my DT and LS files TDLS gives  me following error:

Unhandled Exception: System.NullReferenceException: Object reference not set to an object instance.
   at DTLS.ResourceManager.InitializePartition(RFFile rf, String partition)
   at DTLS.ResourceManager.InitializePartition(String partition)
   at DTLS.ResourceManager.Unpack(String partition, String outfolder)
   at DTLS.ResourceManager.UnpackAll(String outfolder)
   at DTLS.Types.Program.Main(String[] args)

Are my files corrupt or is something wrong here?

**Comment by LemonatedCat** [comment]
Well, i had to use an older build, worked for some reason


Now i have a diffrent problem, i get this error on trying to patch DTLS with the -r option

**Comment by LemonatedCat** [comment]
i found the issue, change this to a request instead, maybe Allow Relative paths and not just full paths

**Comment by Matojeje** [comment]
Thanks for posting this issue, saved me a lot of time
