### ISSUE TITLE
Ness' Forward Air cause errors

### ISSUE THREAD

**Issue by Filuz** [Sammi-Husky/Sm4sh-Tools#67]
Decompiling a fresh, unedited Ness will not show any error.
Compiling with FITC will not show any error, but attempting to decompile with FITD again it will throw this:

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeConditional(Int32 startIndex, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeConditional(Int32 startIndex, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeConditional(Int32 startIndex, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeConditional(Int32 startIndex, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeCommand(Int32 index, UInt32 ident, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeLoop(Int32 startIndex, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.DeserializeCommand(Int32 index, UInt32 ident, List`1& lines)
   at SALT.Moveset.AnimCMD.ACMDScript.Deserialize()
   at FITDecompiler.Program.write_movedef(ACMDScript game, ACMDScript effect, ACMDScript sound, ACMDScript expression, String animname, Boolean unlisted, String outdir)
   at FITDecompiler.Program.decompile_acmd(String mtable, String motionFolder, String output)
   at FITDecompiler.Program.Main(String[] args)
```
Just decompiling and recompiling the fighter without doing any edit is enough to cause this error.
Can be somewhat worked around by using SM4SHcommand to do other edits and never opening forward air.

**Comment by Sammi-Husky** [comment]
Issue is fixed in 98dd079
